const data = {
  products: [
    {
      _id: 1,
      name: 'White Salon',
      slug: 'white_salon',
      category: 'Chair',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Vens',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: 2,
      name: 'Vintage Mirror',
      slug: 'vintage_mirror',
      category: 'Mirror',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Hases',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: 3,
      name: 'Art Chair',
      slug: 'art_chair',
      category: 'Chair',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: 4,
      name: 'Table Coffee',
      slug: 'table_coffee',
      category: 'Table',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Vens',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: 6,
      name: 'Sleep Lamp',
      slug: 'sleep lamp',
      category: 'Lamp',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Hanes',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: 7,
      name: 'Vintage Table',
      slug: 'vintage_table',
      category: 'Table',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Vens',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
